/** Developed by HAFIZ  */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class LOGIN extends javax.swing.JFrame {
    static String username;

    
    public LOGIN() {
        initComponents();
        setResizable(false);
        Passtf.setEchoChar('*');
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        ImgBackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        usertf = new javax.swing.JTextField();
        Passtf = new javax.swing.JPasswordField();
        TglPass = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        LOGINtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMinimumSize(new java.awt.Dimension(778, 460));
        getContentPane().setLayout(null);

        BackPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackPanel.setLayout(null);

        ImgBackPanel.setBackground(new java.awt.Color(128, 0, 0));
        ImgBackPanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LaundryLogin.png"))); // NOI18N
        ImgBackPanel.add(jLabel2);
        jLabel2.setBounds(-160, -30, 440, 540);

        BackPanel.add(ImgBackPanel);
        ImgBackPanel.setBounds(0, 0, 270, 480);

        user.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        user.setText("Username");
        BackPanel.add(user);
        user.setBounds(320, 110, 110, 30);

        pass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pass.setText("Password");
        BackPanel.add(pass);
        pass.setBounds(320, 210, 120, 30);

        Loginbtn.setBackground(new java.awt.Color(128, 0, 0));
        Loginbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Login");
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
        });
        BackPanel.add(Loginbtn);
        Loginbtn.setBounds(320, 340, 100, 40);

        Registerbtn.setBackground(new java.awt.Color(128, 0, 0));
        Registerbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Register Now");
        Registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterbtnMouseClicked(evt);
            }
        });
        BackPanel.add(Registerbtn);
        Registerbtn.setBounds(580, 340, 130, 40);
        BackPanel.add(usertf);
        usertf.setBounds(320, 150, 360, 30);
        BackPanel.add(Passtf);
        Passtf.setBounds(320, 250, 360, 30);

        TglPass.setBackground(new java.awt.Color(255, 255, 255));
        TglPass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TglPass.setText("Show Password");
        TglPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TglPassMouseClicked(evt);
            }
        });
        BackPanel.add(TglPass);
        TglPass.setBounds(320, 290, 130, 22);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(null);

        LOGINtxt.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LOGINtxt.setForeground(new java.awt.Color(255, 255, 255));
        LOGINtxt.setText("Login");
        jPanel1.add(LOGINtxt);
        LOGINtxt.setBounds(220, 10, 80, 50);

        BackPanel.add(jPanel1);
        jPanel1.setBounds(270, 0, 510, 70);

        getContentPane().add(BackPanel);
        BackPanel.setBounds(0, 0, 780, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbtnMouseClicked
        Registration register = new Registration();
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegisterbtnMouseClicked

    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked
        username = usertf.getText();
        String password = Passtf.getText();

        String url = "jdbc:mysql://localhost:3306/laundrysystemdatabase"; 
        String user = "root"; 
        String dbPassword = "SQLreqaw2004"; 

        String sql = "SELECT * FROM login WHERE BINARY Username = ? AND BINARY Password = ?";
        
        if (username.isEmpty()|password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in your login", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try (Connection conn = DriverManager.getConnection(url, user, dbPassword);
            PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, username);
            pstmt.setString(2, password);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login successful!");
                Dashboard dash = new Dashboard();
                dash.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.","Error", JOptionPane.ERROR_MESSAGE);
                Passtf.setText("");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during login. Please try again.");
    }
    }//GEN-LAST:event_LoginbtnMouseClicked

    private void TglPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TglPassMouseClicked
        if (TglPass.isSelected()){
            Passtf.setEchoChar((char)0);
        } else {
            Passtf.setEchoChar('*');
        }
    }//GEN-LAST:event_TglPassMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JPanel ImgBackPanel;
    private javax.swing.JLabel LOGINtxt;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JPasswordField Passtf;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JCheckBox TglPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
