/** Developed by HAFIZ  */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

public class Registration extends javax.swing.JFrame {    

    public Registration() {
        initComponents();
        setResizable(false);
        PassTF.setEchoChar('*');
        VerPassTF.setEchoChar('*');
    }
    
    public void clear(){
        UsernameTF.setText("");
        PassTF.setText("");
        VerPassTF.setText("");
        GmailTF.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        Usernamelbl = new javax.swing.JLabel();
        Passwordlbl = new javax.swing.JLabel();
        BackToLoginbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        UsernameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        VerPass = new javax.swing.JLabel();
        Gmaltxt = new javax.swing.JLabel();
        GmailTF = new javax.swing.JTextField();
        PassTF = new javax.swing.JPasswordField();
        VerPassTF = new javax.swing.JPasswordField();
        ShowPass2 = new javax.swing.JCheckBox();
        ShowPass = new javax.swing.JCheckBox();
        TopBackPanel = new javax.swing.JPanel();
        RegLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        getContentPane().setLayout(null);

        BackPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackPanel.setForeground(new java.awt.Color(255, 255, 255));
        BackPanel.setLayout(null);

        Usernamelbl.setBackground(new java.awt.Color(255, 255, 255));
        Usernamelbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Usernamelbl.setForeground(new java.awt.Color(0, 0, 0));
        Usernamelbl.setText("Username");
        BackPanel.add(Usernamelbl);
        Usernamelbl.setBounds(220, 30, 160, 30);

        Passwordlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Passwordlbl.setForeground(new java.awt.Color(0, 0, 0));
        Passwordlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Passwordlbl.setText("Password");
        BackPanel.add(Passwordlbl);
        Passwordlbl.setBounds(280, 200, 110, 30);

        BackToLoginbtn.setBackground(new java.awt.Color(128, 0, 0));
        BackToLoginbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BackToLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginbtn.setText("Back To Login");
        BackToLoginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToLoginbtnMouseClicked(evt);
            }
        });
        BackPanel.add(BackToLoginbtn);
        BackToLoginbtn.setBounds(250, 320, 170, 40);

        Registerbtn.setBackground(new java.awt.Color(128, 0, 0));
        Registerbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Register");
        Registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterbtnMouseClicked(evt);
            }
        });
        BackPanel.add(Registerbtn);
        Registerbtn.setBounds(520, 320, 170, 40);
        BackPanel.add(UsernameTF);
        UsernameTF.setBounds(220, 60, 500, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterIconY.png"))); // NOI18N
        jLabel1.setText("Iconlbl");
        BackPanel.add(jLabel1);
        jLabel1.setBounds(40, 20, 110, 100);

        VerPass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        VerPass.setText("Verify Password");
        BackPanel.add(VerPass);
        VerPass.setBounds(530, 200, 160, 30);

        Gmaltxt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Gmaltxt.setText("Gmail ");
        BackPanel.add(Gmaltxt);
        Gmaltxt.setBounds(220, 110, 80, 22);
        BackPanel.add(GmailTF);
        GmailTF.setBounds(220, 140, 500, 30);
        BackPanel.add(PassTF);
        PassTF.setBounds(220, 230, 240, 30);
        BackPanel.add(VerPassTF);
        VerPassTF.setBounds(480, 230, 240, 30);

        ShowPass2.setBackground(new java.awt.Color(255, 255, 255));
        ShowPass2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ShowPass2.setText("Show Password");
        ShowPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPass2MouseClicked(evt);
            }
        });
        BackPanel.add(ShowPass2);
        ShowPass2.setBounds(480, 270, 120, 24);

        ShowPass.setBackground(new java.awt.Color(255, 255, 255));
        ShowPass.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ShowPass.setText("Show Password");
        ShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPassMouseClicked(evt);
            }
        });
        BackPanel.add(ShowPass);
        ShowPass.setBounds(220, 270, 160, 24);

        getContentPane().add(BackPanel);
        BackPanel.setBounds(0, 80, 780, 390);

        TopBackPanel.setBackground(new java.awt.Color(128, 0, 0));
        TopBackPanel.setLayout(null);

        RegLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        RegLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegLabel.setText("REGISTRATION FORM");
        RegLabel.setToolTipText("");
        RegLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TopBackPanel.add(RegLabel);
        RegLabel.setBounds(250, 20, 310, 35);

        getContentPane().add(TopBackPanel);
        TopBackPanel.setBounds(0, 0, 780, 80);

        setSize(new java.awt.Dimension(792, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToLoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToLoginbtnMouseClicked
        LOGIN loginpg = new LOGIN();
        loginpg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToLoginbtnMouseClicked

    private void RegisterbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbtnMouseClicked
        String username = UsernameTF.getText();
        String password = PassTF.getText();
        String verpass = VerPassTF.getText();
        String Gmail = GmailTF.getText();
        
        String url = "jdbc:mysql://localhost:3306/laundrysystemdatabase"; 
        String user = "root"; 
        String dbPassword = "SQLreqaw2004"; 

        String sqlInsert = "INSERT INTO login (Username, Password, Gmail) VALUES (?, ?, ?)";
        String sqlSelect = "SELECT * FROM login WHERE Gmail = ?";
        
        if (username.isEmpty()|password.isEmpty()|verpass.isEmpty()|Gmail.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all fields to register", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }   else if (!verpass.equals(password)){
            JOptionPane.showMessageDialog(this, "Passwords dont match!", "Error", JOptionPane.ERROR_MESSAGE);
            PassTF.setText("");
            VerPassTF.setText("");
            return;
        }
        
        try (Connection conn = DriverManager.getConnection(url, user, dbPassword);
                PreparedStatement pstmtInsert = conn.prepareStatement(sqlInsert);
                PreparedStatement pstmtSelect = conn.prepareStatement(sqlSelect)) {
            
            pstmtSelect.setString(1, Gmail);            
            
            pstmtSelect.setString(1, Gmail);
            ResultSet rs = pstmtSelect.executeQuery();
            
            if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Email already exists", "Error", JOptionPane.ERROR_MESSAGE);
            GmailTF.setText("");
            return;
            }
            
            pstmtInsert.setString(1, username);
            pstmtInsert.setString(2, password);
            pstmtInsert.setString(3, Gmail);
            
            int rowsInserted = pstmtInsert.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "You have registered Sucessfully, Thank you!");
                clear();
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error, Please try again.","Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RegisterbtnMouseClicked

    private void ShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPassMouseClicked
        // TODO add your handling code here:
        if (ShowPass.isSelected()){
            PassTF.setEchoChar((char)0);
        } else {
            PassTF.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPassMouseClicked

    private void ShowPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPass2MouseClicked
        // TODO add your handling code here:
        if (ShowPass2.isSelected()){
            VerPassTF.setEchoChar((char)0);
        } else {
            VerPassTF.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPass2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JButton BackToLoginbtn;
    private javax.swing.JTextField GmailTF;
    private javax.swing.JLabel Gmaltxt;
    private javax.swing.JPasswordField PassTF;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JLabel RegLabel;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JCheckBox ShowPass2;
    private javax.swing.JPanel TopBackPanel;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JLabel VerPass;
    private javax.swing.JPasswordField VerPassTF;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
